// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDu6lGR8BHUhfLYEyBNprcm0qlHRmqe7Qg',
    appId: '1:591100228952:web:29850a451b70df442de12d',
    messagingSenderId: '591100228952',
    projectId: 'datn-tvd20215547',
    authDomain: 'datn-tvd20215547.firebaseapp.com',
    storageBucket: 'datn-tvd20215547.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlGig7dz7YcoxfOkAJVKCFu-TtGdDFX08',
    appId: '1:591100228952:android:cfb2fd62618c28cb2de12d',
    messagingSenderId: '591100228952',
    projectId: 'datn-tvd20215547',
    storageBucket: 'datn-tvd20215547.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkHpDYnefDZdSNOoh_OF5GZvvsISmybXk',
    appId: '1:591100228952:ios:f30b4260068c394d2de12d',
    messagingSenderId: '591100228952',
    projectId: 'datn-tvd20215547',
    storageBucket: 'datn-tvd20215547.firebasestorage.app',
    iosBundleId: 'com.example.mobileProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCkHpDYnefDZdSNOoh_OF5GZvvsISmybXk',
    appId: '1:591100228952:ios:f30b4260068c394d2de12d',
    messagingSenderId: '591100228952',
    projectId: 'datn-tvd20215547',
    storageBucket: 'datn-tvd20215547.firebasestorage.app',
    iosBundleId: 'com.example.mobileProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDu6lGR8BHUhfLYEyBNprcm0qlHRmqe7Qg',
    appId: '1:591100228952:web:584fba92a68e79052de12d',
    messagingSenderId: '591100228952',
    projectId: 'datn-tvd20215547',
    authDomain: 'datn-tvd20215547.firebaseapp.com',
    storageBucket: 'datn-tvd20215547.firebasestorage.app',
  );
}
